volumes:
  postgres_data: {}
  prometheus_data: {}
  grafana_data: {}

services:
  postgres:
    image: docker.io/library/postgres:18
    volumes:
    - postgres_data:/var/lib/postgresql/18/docker:delegated
    command:
    - postgres
    - -c
    - shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: '5432'
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: aidbox

  aidbox:
    image: docker.io/healthsamurai/aidboxone:edge
    #pull_policy: always
    depends_on:
    - postgres
    ports:
    - 8080:8080
    volumes:
      - ./:/resources
    environment:
      BOX_INIT_BUNDLE: 'file:///resources/init-bundle.json'
      BOX_ADMIN_PASSWORD: admin
      BOX_BOOTSTRAP_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: '#{:fhir-datetime}'
      BOX_DB_DATABASE: aidbox
      BOX_DB_HOST: postgres
      BOX_METRICS_PORT: 8765
      BOX_DB_PASSWORD: aidbox
      BOX_DB_PORT: '5432'
      BOX_DB_USER: aidbox
      BOX_FHIR_BUNDLE_EXECUTION_VALIDATION_MODE: limited
      BOX_FHIR_COMPLIANT_MODE: 'true'
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: 'true'
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: 'true'
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: 'true'
      BOX_FHIR_SEARCH_CHAIN_SUBSELECT: 'true'
      BOX_FHIR_SEARCH_COMPARISONS: 'true'
      BOX_CACHE_REPLICATION_DISABLED: 'true'
      BOX_FHIR_TERMINOLOGY_ENGINE: hybrid
      BOX_FHIR_TERMINOLOGY_ENGINE_HYBRID_EXTERNAL_TX_SERVER: https://tx.health-samurai.io/fhir
      BOX_FHIR_TERMINOLOGY_SERVICE_BASE_URL: https://tx.health-samurai.io/fhir
      BOX_MODULE_SDC_STRICT_ACCESS_CONTROL: 'true'
      BOX_ROOT_CLIENT_SECRET: eEwmEgWjyc
      BOX_RUNME_UUID: 19c23430-b6a7-4fd3-b83a-418c5d850174
      BOX_SEARCH_INCLUDE_CONFORMANT: 'true'
      BOX_SETTINGS_MODE: read-write
      BOX_WEB_BASE_URL: http://localhost:8080
      BOX_LICENSE: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvZmZsaW5lIjpmYWxzZSwiY3JlYXRvciI6eyJpZCI6ImQxYzRiNDIyLWUwMjktNDFlMi05MDY0LTRkZTE0NmU2MzUxNiIsInJlc291cmNlVHlwZSI6IlVzZXIifSwia2V5Ijoib25saW5lLTIwMjIwNTI0LTE0MzY0NyIsIm5hbWUiOiJBaWRib3ggbG9jYWwgIzI2NDU3IiwiZXhwaXJhdGlvbiI6IjIxMjUtMDEtMDVUMDA6MDA6MDAuMDAwWiIsInR5cGUiOiJkZXZlbG9wbWVudCIsImNyZWF0ZWQiOiIyMDI2LTAxLTI5VDE0OjAxOjA2LjkyMloiLCJtYXgtaW5zdGFuY2VzIjoyMCwibWF4LWRiLXNpemUiOjUzNjg3MDkxMjAwMCwicHJvZHVjdCI6ImFpZGJveCIsInByb2plY3QiOnsiaWQiOiJiNDkzNTRlOS01NmEwLTQ5ODgtOTg4Zi05NWJhMjU5MGVmZWMiLCJyZXNvdXJjZVR5cGUiOiJQcm9qZWN0In0sInN0YXR1cyI6ImFjdGl2ZSIsImlkIjoiNWI0ZGEzOWQtN2E3Yi00ZTI4LWI3MGYtZWEzNWExMTYxNzE0IiwiaW5mbyI6eyJob3N0aW5nIjoic2VsZi1ob3N0ZWQifSwiaXNzdWVyIjoiaHR0cHM6Ly9haWRib3guYXBwIn0.YT-yc18dLOVWiYeqrEEk2PWgMb1KBW_8gzX7CoPgRjOvVp5HVA45LnYIfEj3eXTuXIADn7AehNTPHfIoSV1UBbEKL4FvPzlqheQtm0uX7NfUe3xVNzxzJcF0-w_y0eqSc7oC8-6EXubYDLmDAVgQGETGPb7DvI0Ez6BkgL1C46s
      BOX_WEB_PORT: 8080
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 90
      start_period: 30s

  prometheus:
    image: prom/prometheus:v3.9.1
    volumes:
      - ./prometheus:/etc/prometheus:cached
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    entrypoint: ['/bin/bash']
    command:
      - -c
      - |
        curl -o /tmp/aidbox.json https://grafana.com/api/dashboards/24752/revisions/3/download && exec /run.sh
    environment:
      V: v5
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SERVER_ROOT_URL: http://localhost:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    image: grafana/grafana:12.3.1
    ports:
      - 3000:3000