services:
  hl7-app:
    build: .
    ports:
      - "3000:${PORT}"
      - "2575:${MLLP_RECEIVER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
  aidbox:
    image: healthsamurai/aidboxone:edge
    restart: unless-stopped
    pull_policy: if_not_present
    env_file:
      - .env
    environment:
      AIDBOX_TERMINOLOGY_SERVICE_BASE_URL: https://tx.fhir.org/r4
      AIDBOX_FHIR_PACKAGES: hl7.fhir.r4b.core#4.3.0
      AIDBOX_LICENSE: ${AIDBOX_LICENSE}
      AIDBOX_FHIR_SCHEMA_VALIDATION: true
      AIDBOX_CREATED_AT_URL: https://aidbox.app/ex/createdAt
      AIDBOX_CLIENT_ID: ${AIDBOX_CLIENT_ID}
      AIDBOX_CLIENT_SECRET: ${AIDBOX_CLIENT_SECRET}
      AIDBOX_CORRECT_AIDBOX_FORMAT: true
      AIDBOX_ADMIN_PASSWORD: ${AIDBOX_ADMIN_PASSWORD}
      AIDBOX_COMPLIANCE: enabled
      AIDBOX_PORT: ${AIDBOX_PORT}
      BOX_SEARCH_FHIR__COMPARISONS: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: false
      PGHOST: aidbox-db
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: "#{:fhir-datetime}"
      PGUSER: aidbox
      PGDATABASE: aidbox
      PGPASSWORD: aidbox
      PGPORT: 5432
      BOX_SEARCH_INCLUDE_CONFORMANT: true
    ports:
      - 8789:${AIDBOX_PORT}
    healthcheck:
      test: curl -f http://localhost:8789/health
      interval: 2s
      timeout: 10s
      retries: 30
    depends_on:
      aidbox-db:
        condition: service_healthy
    links:
      - aidbox-db
    volumes:
      - ./.aidbox/zen-package.edn:/aidbox-project/zen-package.edn
      - ./.aidbox/zrc:/aidbox-project/zrc
      - ./.aidbox/zen-packages:/aidbox-project/zen-packages
    profiles:
      - all
      - local
  aidbox-db:
    image: healthsamurai/aidboxdb:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: 5432
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: aidbox
    healthcheck:
      test: pg_isready -d aidbox -U aidbox
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - hl7-app-data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
    profiles:
      - all
      - local