global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aidbox'

scrape_configs:
  - job_name: aidbox
    honor_labels: true
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'aidbox:8765' ]

  - job_name: aidbox-minutes
    honor_labels: true
    scrape_interval: 1m
    metrics_path: /metrics/minutes
    static_configs:
      - targets: [ 'aidbox:8765' ]

  - job_name: aidbox-hours
    honor_labels: true
    scrape_interval: 10m
    scrape_timeout: 30s
    metrics_path: /metrics/hours
    static_configs:
      - targets: [ 'aidbox:8765' ]