name: Deploy Aidbox Forms Smart Launch 2

on:
  push:
    branches:
      - main
    paths:
      - 'aidbox-forms/aidbox-forms-smart-launch-2/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define env variables
        run: |
          echo "IMAGE=${GITHUB_REPOSITORY@L}-aidbox-forms-smart-launch-2" >>${GITHUB_ENV}

      - name: Publish image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: aidbox-forms//aidbox-forms-smart-launch-2
          tags: ghcr.io/${{ env.IMAGE }}
          push: true
